language: java
jdk:
  - oraclejdk8

install: true
script: mvn -B -q verify

sudo: false

before_install:
  - wget http://supergsego.com/apache/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
  - unzip -qq apache-maven-3.5.3-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.3
  - export PATH=$M2_HOME/bin:$PATH

cache:
  directories:
  - $HOME/.m2
