language: java
jdk:
  - openjdk8
  - openjdk11

env:
  - # use Jackson versions from POM
  - JACKSON_VERSIONS="-Ddep.jackson.version=2.9.9 -Ddep.jackson-databind.version=2.9.9.3"
  - JACKSON_VERSIONS="-Ddep.jackson.version=2.9.10 -Ddep.jackson-databind.version=2.9.10.2"

script: mvn -B -q verify $JACKSON_VERSIONS

sudo: false

cache:
  directories:
  - $HOME/.m2
